### ISSUE TITLE
GetResponse sometimes returns a NIL object

### ISSUE THREAD

**Issue by hoisie** [alphazero/Go-Redis#1]
I have a long-running web service that uses Go-Redis. Once on a while I get the following stack trace:

SIGSEGV: segmentation violation
Faulting address: 0x20
PC=0x40a44d

redis·_connHdl·ServiceRequest+0x28b /home/mike/workspace/Go-Redis/src/pkg/redis/connection.go:263
        redis·_connHdl·ServiceRequest(0x7947e1a0, 0x7fae, 0x4b5d60, 0x0, 0x785cd7d0, ...)
redis·_syncClient·Llen+0xfc /home/mike/workspace/Go-Redis/src/pkg/redis/synchclient.go:442
        redis·_syncClient·Llen(0x79479930, 0x7fae, 0x785d7ba0, 0x7fae, 0x16, ...)

It seems that GetResponse in protocol.go sometimes returns a nil object. However, connection.go always assumes it's not nil. Perhaps a check should be added in connection.go that tests if the response is nil?

**Comment by hoisie** [comment]
I believe this is an issue with concurrency and conflucing reads, see issue (2)

**Comment by alphazero** [comment]
That's correct - protocol is supplying specific response types and if used concurrently a client may be attempting to read data that simply is not there.
