### ISSUE TITLE
Go Redis will get slow query (1 s) when application load is heavy

### ISSUE THREAD

**Issue by Codefor** [alphazero/Go-Redis#29]
I have a web API written in Go using Go redis.
the API will connection to redis,fetch the newest 5 items in a 20-items list,do some iter computation,and reture the result.
(I will use RPUSH to store the list )

However,when a use http_load to run benchmark,the log shows that redis is slow.
The slow rate is about 0.1%.
Every time I run the benchmark,there will be slow log

When I use Python script ,the redis response always in ms!
How is that?

the init connection code is as this:

```
spec := redis.DefaultSpec().Host(host).Port(port).Db(db)
conn, e := redis.NewAsynchClientWithSpec(spec)
if e != nil {
    log.Fatal("Error creating client for worker: ", e)
    os.Exit(1)
}
```

And the Lrange code is as this:

```
futureData,err = (*Redis).Lrange("my redis key",- 5,-1)
timeout := 100*time.Millisecond
t := time.Now()
mydata,err,timedout  := futureData.TryGet(timeout)
if time.Since(t) > time.Second {
    log.Println("slow redis query[fetch result]"）
}
```

**Comment by alphazero** [comment]
Well the usage is correct, but I can't speak to the usage of micro-benchmark you are using. For one, you did not provide that, and more importantly, micro-benchmarks are not definitive in terms of performance benchmarks.
