### ISSUE TITLE
Makefiles don't conform with new go release

### ISSUE THREAD

**Issue by JonasOberhauser** [alphazero/Go-Redis#3]
Please change the .$(GOARCH) to .inc. Thank you!

**Comment by alphazero** [comment]
Go ahead and make the change, insure it is correct and I'll pull from you.  Thanks.

**Comment by mortimer** [comment]
I've made modifications to bring Go-Redis up-to-date with the latest Go release (and also restored the benchmark tests).

https://github.com/mortimer/Go-Redis/commits/master

**Comment by alphazero** [comment]
My apologies for the recent blackout.  Had been deep in prof. work and had no time at all to devote to personal projects.  I'm in process of updating both redis clients.  Also need to catch up with Go (!) and then push the Go client up to latest Redis.  

Will be rolling in yours as 1st step.  Thank you for contributing.

/R

**Comment by alphazero** [comment]
Make files and structure changed and work with Go1.
