### ISSUE TITLE
Support goinstall

### ISSUE THREAD

**Issue by mperham** [alphazero/Go-Redis#6]
goinstall allows you to auto-install github repos.  I'm new to Go so I'm not sure what the underlying problem is.  This would make it easy for noobs like me to install and use your project quickly.

http://golang.org/cmd/goinstall/

```
> goinstall -u github.com/alphazero/Go-Redis
goinstall: github.com/alphazero/Go-Redis: package has no files
```

**Comment by alphazero** [comment]
Hi Mike,

Thanks, I'll look into it.

/R

**Comment by alphazero** [comment]
Project now reflects go install prefs, but there is the issue of the (imo BUG) in Go install that demands repo name and package names to be identical.  Closing as changing repo-name, or, changing package name (go-redis is illegal package name in Go) are both non-options.
